-- MySQL Script generated by MySQL Workbench
-- mié 15 abr 2015 17:06:09 CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` CHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `numeroTelefonico` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `numero` INT(10) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `idCuenta` BIGINT(20) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `idClientes` INT NOT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_cuenta_clientes_idx` (`idClientes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operacionescuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operacionescuenta` (
  `idOperacionesCuenta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fechaOperacion` DATE NOT NULL,
  `tipoDeMovimiento` CHAR(1) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `idCuenta` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idOperacionesCuenta`),
  INDEX `fk_operacionescuenta_cuenta1_idx` (`idCuenta` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
