package practica.entidad;
// Generated 15/04/2015 05:32:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="mydb"
)
public class Clientes  implements java.io.Serializable {


     private Integer idClientes;
     private String contrasenia;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String numeroTelefonico;
     private String calle;
     private String colonia;
     private int numero;

    public Clientes() {
    }

    public Clientes(String contrasenia, String nombre, String apellidoPaterno, String apellidoMaterno, String numeroTelefonico, String calle, String colonia, int numero) {
       this.contrasenia = contrasenia;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.numeroTelefonico = numeroTelefonico;
       this.calle = calle;
       this.colonia = colonia;
       this.numero = numero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idClientes", unique=true, nullable=false)
    public Integer getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(Integer idClientes) {
        this.idClientes = idClientes;
    }

    
    @Column(name="contrasenia", nullable=false, length=10)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidoPaterno", nullable=false, length=45)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="apellidoMaterno", nullable=false, length=45)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    
    @Column(name="numeroTelefonico", nullable=false, length=45)
    public String getNumeroTelefonico() {
        return this.numeroTelefonico;
    }
    
    public void setNumeroTelefonico(String numeroTelefonico) {
        this.numeroTelefonico = numeroTelefonico;
    }

    
    @Column(name="calle", nullable=false, length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="colonia", nullable=false, length=45)
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }




}


