package practica.entidad;
// Generated 15/04/2015 05:32:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operacionescuenta generated by hbm2java
 */
@Entity
@Table(name="operacionescuenta"
    ,catalog="mydb"
)
public class Operacionescuenta  implements java.io.Serializable {


     private Long idOperacionesCuenta;
     private Date fechaOperacion;
     private char tipoDeMovimiento;
     private double cantidad;
     private long idCuenta;

    public Operacionescuenta() {
    }

    public Operacionescuenta(Date fechaOperacion, char tipoDeMovimiento, double cantidad, long idCuenta) {
       this.fechaOperacion = fechaOperacion;
       this.tipoDeMovimiento = tipoDeMovimiento;
       this.cantidad = cantidad;
       this.idCuenta = idCuenta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idOperacionesCuenta", unique=true, nullable=false)
    public Long getIdOperacionesCuenta() {
        return this.idOperacionesCuenta;
    }
    
    public void setIdOperacionesCuenta(Long idOperacionesCuenta) {
        this.idOperacionesCuenta = idOperacionesCuenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaOperacion", nullable=false, length=10)
    public Date getFechaOperacion() {
        return this.fechaOperacion;
    }
    
    public void setFechaOperacion(Date fechaOperacion) {
        this.fechaOperacion = fechaOperacion;
    }

    
    @Column(name="tipoDeMovimiento", nullable=false, length=1)
    public char getTipoDeMovimiento() {
        return this.tipoDeMovimiento;
    }
    
    public void setTipoDeMovimiento(char tipoDeMovimiento) {
        this.tipoDeMovimiento = tipoDeMovimiento;
    }

    
    @Column(name="cantidad", nullable=false, precision=22, scale=0)
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="idCuenta", nullable=false)
    public long getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(long idCuenta) {
        this.idCuenta = idCuenta;
    }




}


